google_chrome_profiles: add path column
macadmins/osquery-extension pull request #60
Opened 2024-12-31 14:17 UTC by slai

There is currently no column that can be used to link rows returned by the _google_chrome_profiles_ table with the rows returned by the OSQuery built-in _chrome_extensions_ table. This is useful for determining the email, and therefore the Google Account, associated with the profile, which can be used as a proxy for whether the profile is a work or non-work one.

This PR adds a _path_ column to the _google_chrome_profiles_ table. This is the path to the profile's directory, and should match _profile_path_ column in the _chrome_extensions_ table, allowing these two tables to be joined together. It does this by pulling out the profile's directory name from the same dictionary used to get the existing data, combines it with the Chrome user data directory path, and finally checks that it exists before returning it. It is possible for this column to be empty, if for whatever reason, the computed path does not exist.

```
osquery> select * from google_chrome_profiles;
+----------+------------------------+------------------+-----------+-----------------------------------------------------------------+
| username | email                  | name             | ephemeral | path                                                            |
+----------+------------------------+------------------+-----------+-----------------------------------------------------------------+
| user1    | user1@test.example.com | test.example.com | 0         | /Users/user/Library/Application Support/Google/Chrome/Default   |
| user2    | user2@example.com      | example.com      | 0         | /Users/user/Library/Application Support/Google/Chrome/Profile 1 |
+----------+------------------------+------------------+-----------+-----------------------------------------------------------------+
```

2025-01-16 20:58 UTC, grahamgilbert requested changes

2025-01-16 20:58 UTC, grahamgilbert commented on tables/chromeuserprofiles/chrome_user_profiles.go
> +func profilePathIfExists(localStatePath, profileDir string) string {
Please write a unit test for this function

2025-01-16 20:58 UTC, grahamgilbert commented on tables/chromeuserprofiles/chrome_user_profiles_test.go
> +	// Create a dummy directory for one of the profiles - the name is the
Please use more inclusive language here. Placeholder is a decent alternative here.

2025-01-16 20:58 UTC, grahamgilbert commented on tables/chromeuserprofiles/chrome_user_profiles.go
> +		// If there's an error of any kind, assume the profile path doesn't
Perhaps it would be better to handle the specific not found error and surface other errors?

2025-01-17 19:37 UTC, slai commented on tables/chromeuserprofiles/chrome_user_profiles.go
> +		// If there's an error of any kind, assume the profile path doesn't
I've propagated the error up to the `generateForPath` function, but I've noticed that `GoogleChromeProfilesGenerate` currently ignores all errors returned from all of the functions it calls.

If we surface the errors returned from my changes, I think we should also surface the other possible errors from the functions called. But this would be a change in how this table works, from never returning errors in any scenario, to returning errors in some scenarios.

Thoughts?

2025-02-20 02:03 UTC, merged